# config.yaml pour SVM
experiment_name: "svm_experiment_01"

data:
  name: "fashion_mnist"            # Options: fashion_mnist, mnist, cifar10, svhn
  selected_classes: [3, 8]         # Classes binaires à distinguer

svm:
  use_pca: true                    # Active la réduction de dimension
  pca_components: 50              # Nombre de composantes à conserver
  save_path: "checkpoints/svm"    # Chemin pour sauvegarder le modèle
  optimize: true                  # Utilise Optuna pour rechercher les meilleurs hyperparamètres
  n_trials: 30                    # Nombre d'essais d'Optuna

seed: 42                          # Pour la reproductibilité
