experiment_name: qkernel_fashionmnist_v1

dataset: fashion_mnist
selected_classes: [3, 8]   # Par exemple, pullovers vs bags dans Fashion-MNIST
method: qks                # ou 'fidelity'
kfold: 5
optimize: true             # active l’optimisation Optuna
use_pca:  true

kernel: rbf                # utilisé si optimize: false
C: 1.0                     # idem
gamma: scale               # idem
