experiment_name: cnn_fashionmnist_experiment

dataset:
  name: fashion_mnist
  binary_classes: [3, 8]  # Pull-over vs Sandal par ex. (classes 3 et 8)

training:
  batch_size: 64
  epochs: 20
  learning_rate: 0.001
  kfold: 5
  early_stopping: 5

model:
  in_channels: 1  # Fashion-MNIST est en niveaux de gris comme MNIST

checkpoint:
  save_dir: "checkpoints"
  subdir: "cnn_fashionmnist_experiment"

scheduler: "step"
