experiment_name: "cnn_cifar10_exp"

dataset:
  name: "cifar10"
  binary_classes: [3, 8]

training:
  batch_size: 64
  epochs: 40
  learning_rate: 0.001
  kfold: 3
  early_stopping: 15
  scheduler: "StepLR"
  scheduler_params:
    step_size: 10
    gamma: 0.5

model:
  in_channels: 3  # ✅ CIFAR-10 est RGB avec 3 canaux
  grayscale: false   # 🔥 Ajout clé ici : permet de choisir depuis le yaml

