experiment_name: "hybrid_qcnn_cifar10_exp"

dataset:
  name: "cifar10"
  binary_classes: [3, 8]

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.0005
  kfold: 3
  early_stopping: 5
  scheduler: "StepLR"
  scheduler_params:
    step_size: 5
    gamma: 0.5

quantum:
  n_qubits: 4
  layers: 2
  backend: "lightning.qubit"
