experiment_name: "classical_cifar10_exp"

dataset:
  name: "cifar10"
  binary_classes: [3, 8]

training:
  batch_size: 64
  epochs: 20
  learning_rate: 0.001
  kfold: 5
  early_stopping: 5

scheduler: "StepLR"
scheduler_params:
  step_size: 10
  gamma: 0.5
