experiment_name: "classical_svhn_exp"

dataset:
  name: "svhn"
  binary_classes: [3, 8]

training:
  batch_size: 64
  epochs: 50
  learning_rate: 0.0005
  kfold: 3
  early_stopping: 5
  scheduler: "StepLR"

model:
  in_channels: 3  # CIFAR-10 images sont RGB, donc 3 canaux ; mets 1 pour MNIST/Fashion-MNIST
  hidden_sizes: [128, 64, 32]

seed: 42