experiment_name: "mlp_baseline_v1"

dataset:
  name: "fashion_mnist"             # Options: mnist, fashion_mnist, cifar10, svhn
  selected_classes: [3, 8]          # Binaire : première classe = 0, seconde = 1

model:
  input_size: 784                   # 28x28 images aplaties
  hidden_size: 128

training:
  batch_size: 64
  epochs: 30
  learning_rate: 0.001
  kfold: 5
  scheduler: "cosine"              # Options: step, cosine, none
  early_stopping: 5                # Patience in epochs

checkpoint:
  save_dir: "checkpoints"
  subdir: "experiment_mlp_v1"

seed: 42
